# Generated by Django 4.1.4 on 2022-12-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ManyToManyField(blank=True, to="projects.client"),
        ),
        migrations.AlterField(
            model_name="project",
            name="team_divison",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SaaS", "SaaS"),
                    ("Solutions", "Solutions"),
                    ("India", "India"),
                    ("US Health", "US Health"),
                    ("GSO", "GSO"),
                ],
                max_length=50,
            ),
        ),
    ]
