# Generated by Django 4.1.4 on 2022-12-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_client_alter_project_team_divison"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="team_divison",
            new_name="team_division",
        ),
    ]
