# Generated by Django 4.1.4 on 2022-12-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_team_divison_project_team_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
