# Generated by Django 4.1.4 on 2022-12-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, upload_to="uploads/images"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tag",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
