--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-17 16:56:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 239 (class 1259 OID 43371)
-- Name: projects_client; Type: TABLE; Schema: public; Owner: geodimagiadmin
--

CREATE TABLE public.projects_client (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    logo character varying(100) NOT NULL
);


ALTER TABLE public.projects_client OWNER TO geodimagiadmin;

--
-- TOC entry 238 (class 1259 OID 43370)
-- Name: projects_client_id_seq; Type: SEQUENCE; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE public.projects_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4252 (class 0 OID 43371)
-- Dependencies: 239
-- Data for Name: projects_client; Type: TABLE DATA; Schema: public; Owner: geodimagiadmin
--

COPY public.projects_client (id, name, logo) FROM stdin;
4	Mercy Corps	
5	ACDI	
6	Ariel Glaser	
7	Baylor College of Medicine	
8	City Of Philadelphia	
9	Engender Health	
10	Food for the Hungry	
11	GDIS	
12	GiZ	
13	Health in Harmony	
14	IPE Global Limited	
15	Bill and Melinda Gates Medical Research Institute	
17	Ministry of Health of Malawi	
18	MSH	
19	National Institute of Health	
20	SAfA	
21	Sinai Health System	
22	Terre des Hommes	
23	Tuba City Regional Health Care Corporation	
24	UNCDF	
25	UNICEF	
26	Vermont Care Network	
27	World Vision Canada	
29	Colorado Department of Public Health & Environment	
30	Alaska Department of Health and Social Services	
31	Colorado Behavioral Health Administration	
32	New Jersey Department of Health	
33	New York Comunicable Disease	
34	Philadelpha Department of Public Health	
35	Vermont State	
36	Department of Ceviche	
\.


--
-- TOC entry 4258 (class 0 OID 0)
-- Dependencies: 238
-- Name: projects_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: geodimagiadmin
--

SELECT pg_catalog.setval('public.projects_client_id_seq', 36, true);


--
-- TOC entry 4103 (class 2606 OID 43375)
-- Name: projects_client projects_client_pkey; Type: CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_client
    ADD CONSTRAINT projects_client_pkey PRIMARY KEY (id);


-- Completed on 2023-02-17 16:56:47

--
-- PostgreSQL database dump complete
--

