--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-17 17:38:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 241 (class 1259 OID 43377)
-- Name: projects_location; Type: TABLE; Schema: public; Owner: geodimagiadmin
--

CREATE TABLE public.projects_location (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    address character varying(100) NOT NULL,
    city character varying(50) NOT NULL,
    country character varying(50) NOT NULL
);


ALTER TABLE public.projects_location OWNER TO geodimagiadmin;

--
-- TOC entry 240 (class 1259 OID 43376)
-- Name: projects_location_id_seq; Type: SEQUENCE; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE public.projects_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4253 (class 0 OID 43377)
-- Dependencies: 241
-- Data for Name: projects_location; Type: TABLE DATA; Schema: public; Owner: geodimagiadmin
--

COPY public.projects_location (id, name, location, address, city, country) FROM stdin;
7	ACDI Project Office	0101000020E6100000E2F0EF7F47D2EABF01E7B7C1A3CE2240	Louisville	Tamale	Ghana
55	BAART Programs Berlin	0101000020E61000004827F573192452C089B35966A51A4640	617 Comstock Rd Suite 5	Berlin	United States of America
8	Dimagi Cambridge Office	0101000020E6100000345F759E90C651C02621C2E8B92E4540	585 Massachusetts Ave	Cambridge	United States of America
9	Dimagi Cape Town Office	0101000020E61000002CFBF4E1EB6A324056A69D4E7EF740C0	123 Hope St	Cape Town	South Africa
10	Dimagi New Delhi Office	0101000020E61000008577F4A20E4A53407269849602913C40	D-1, 28, Paschimi Marg, Block D	New Dehli	India
11	ACH Office	0101000020E610000079EDF48F508552C06037D69DCAA71240	Bogota	Bogota	Colombia
12	Ariel Glaser	0101000020E61000006E43F61FA449404079C16C5B19F639C0	Maputo	Maputo	Mozambique
13	TPT Mbabane	0101000020E61000004860ED29BF243F40D612773837533AC0	Mbabane	Mbabane	Eswatini
14	TPT Maseru	0101000020E6100000EB91EF93A87A3B40FC2F1ACCB24F3DC0	Maseru	Maseru	Lesotho
15	TPT Dodoma	0101000020E6100000FF50F5296CDF41403DC9B21A0CB918C0	Dodoma	Dodoma	Tanzania
16	TPT Kampala	0101000020E61000003443F618414A4040D93C06AD1054D43F	Kampala	Kampala	Uganda
17	TPT Lilongwe	0101000020E610000033E8F58F40E240402EFEB6BA7BF92BC0	Lilongwe	Lilongwe	Malawi
18	Philadelphia Office	0101000020E61000001AC4F4AA4ACA52C0A8D3539796F84340	Philadelphia	Philadelphia	United States of America
19	Karnataka Office	0101000020E61000000D6764D66D655340DBC340B8DCEF2940	Bengaluru	Bengaluru	India
20	Jharkhand	0101000020E6100000F83EF3ECF3545540296E088BB65E3740	Ranchi	Ranchi	India
21	Madhya Pradesh	0101000020E610000073A9F4884EF75240480FF00844B63640	Indore	Indore	India
22	Chhattisgarh	0101000020E61000004FCC33E39B6854400FCC925A5A3D3540	Raipur	Raipur	India
23	Assam	0101000020E61000007748F226FFEF564099136832792C3A40	Guwahati	Guwahati	India
24	Odisha	0101000020E6100000992B73A4C875554059AEA9872D473440	Bhubaneswar	Bhubaneswar	India
25	Amhara	0101000020E610000067D3F4EFC3B142407A6CBC291C2A2740	Bahir Dar	Bahir Dar	Ethiopia
26	Goa	0101000020E610000088F63492D3745240BF98C5455EFE2E40	Panaji	Panaji	India
27	Poltava	0101000020E6100000A4ABF5A6B6454140C6116A9F41CB4840	Poltava	Poltava	Ukraine
28	HIH Brazil	0101000020E6100000DC14EEFF7FF84DC0DF4B1C7CB54C09C0	Brazil	Brazil	Brazil
29	HIH Indonesia	0101000020E6100000EEF4EEEF2C7B5C40F10C1DDFCFB101C0	Palangkaraya	Palangkaraya	Indonesia
30	HIH Madagascar	0101000020E6100000F702F1BF8D1149405EBE99094C222FC0	Masoala	Masoala	Madagascar
31	SAMVEG Jharkhand	0101000020E6100000F23F339120535540ADBD006BC1543740	Ranchi	Ranchi	India
32	SAMVEG Uttarakhand	0101000020E61000000456F40B40825340006C8F0775513E40	Dehradun	Dehradun	India
33	SAMVEG Madhya Pradesh	0101000020E610000070A9B4D92EF75240DD996496CBB83640	Indore	Indore	India
34	TB XBOS Trial South Africa	0101000020E610000048FEF4DFFD693240BC35AC2ADEF640C0	Cape Town	Cape Town	South Africa
35	TB XBOS Trial Phillipines	0101000020E61000001EEAEDF58E3E5E4045A8A3A2E02E2D40	Manila	Manila	Phillipines
36	TB XBOS Trial Peru	0101000020E61000004B7CF48C964153C058EFB92A362728C0	Lima	Lima	Peru
37	TB XBOS Trial Kenya	0101000020E6100000CEFFF4F74267424082A6ED908896F4BF	Nairobi	Nairobi	Kenya
38	TB XBOS Trial Uganda	0101000020E61000007E42F6F5DB4A40405C4724B475AED23F	Kampala	Kampala	Uganda
39	TB XBOS Trial Vietnam	0101000020E6100000882AF0225B765A40574DFCD34F053540	Hanoi	Hanoi	Vietnam
40	Cash Program 2.0 Colombia	0101000020E6100000ABECF4F76D8752C031740F4C93801240	Colombia	Colombia	Colombia
41	cStock Malawi	0101000020E61000003CE875F1C8E140405528E572B3F92BC0	Lilongwe	Lilongwe	Malawi
42	ACCESS Madagascar	0101000020E61000000FC9F1C588C6474099C5E3AFC8E932C0	Antananarivo	Antananarivo	Madagascar
43	IHSA Benin	0101000020E6100000B672F3EFB7060540FDD35CEB55F91940	Porto-Novo	Porto-Novo	Benin
44	Massachusetts General Hospital	0101000020E61000008160F58567C451C0175E569F6E2E4540	55 Fruit St	Boston	United States of America
45	Montefiore Medical Center	0101000020E61000006FF4F45CAE7852C0CE0EEDE5486B4440	1776 Hoe Ave	New York City	United States of America
46	YouthAgriApp-Ethiopia	0101000020E61000009668F4AC83614340970A530033E92140	Addis Ababa	Addis Ababa	Ethiopia
48	Goa Sangath-Mental Health	0101000020E6100000B4F7F4CFF47352406FCCB306AFF12E40	Panaji	Panaji	India
47	Bhopal Sangath-Mental Health	0101000020E6100000866DF4291C5B53405BC99776233D3740	Bhopal	Bhopal	India
49	E-IMNCI Application Jharkhand	0101000020E6100000ED3EF34FEB54554030C65BCD235E3740	Ranchi	Ranchi	India
50	Navajo Nation	0101000020E61000008DADEFFF3F4A5BC0881770F24D024240	Navajo Nation	Navajo Nation	United States of America
51	Zinder FInancial Education Scale Up	0101000020E6100000813FF59207F9214062A5EFF087A72B40	Zinder	Zinder	Niger
52	Tahoua FInancial Education Scale Up	0101000020E6100000A26EF30792051540DCB47B0B02CB2D40	Tahoua	Tahoua	Niger
53	Agadez Financial Education Scale Up	0101000020E6100000E5F3ECFFF3DC1F40274738E883F33040	Agadez	Agadez	Niger
54	Jamaica COVID-19 Vaccine Rollout	0101000020E61000000A8674C3673253C0B754B328D0F83140	Kingston	Kingston	Jamaica
56	BAART St Albans	0101000020E61000008E12F5B51E4652C0244995F36F664640	242 S Main St	St Albans City	United States of America
57	BAART St Johnsbury	0101000020E6100000223CF5E9C60052C07DAE416116394640	1097 Hospital Dr	St Johnsbury	United States of America
58	BAART Newport	0101000020E61000001036F58ADD0C52C031538735707A4640	475 Union St	Newport	United States of America
59	Howard Center Chittenden Clinic	0101000020E61000002310F58E5E4B52C0230B3F8AA73A4640	75 San Remo Dr	South Burlington	United States of America
60	Brattleboro Comprehensive Treatment Center	0101000020E61000006C28750B992352C05E24016F8C6F4540	16 Town Crier Dr	Brattleboro	United States of America
61	Habit OPCO – West Lebanon	0101000020E6100000F630F5BBB31452C080A05C086CD04540	254 N Plainfield Rd	West Lebanon	United States of America
62	West Ridge Center	0101000020E6100000AA177584503E52C0791F3BF9BBCC4540	Howe Center, 1 Scale Ave Building 10	Rutland	United States of America
63	Technical Advisory Service Mali	0101000020E610000064E1ECFF40F91FC0E15ED46732492940	Bamako	Bamako	Mali
65	Colorado Department of Public Health	0101000020E6100000F77D113C0B3F5AC0FA63933E73DE4340	4300 Cherry Creek S Dr	Denver	United States of America
66	Alaska DHSS Office	0101000020E61000000010FF477FBC62C0984F37BC46974E40	4501 Business Park Blvd # 24	Alaska	United States of America
67	CO BHA Office	0101000020E6100000000000C010425AC01173A87AD9D14340	3824 W Princeton Cir	Denver	United States of America
68	NJ Department of Health Office	0101000020E610000027D3F41158B052C0B7E30151F61B4440	369 S Warren St	Trenton	United States of America
69	NY CDCMS Office	0101000020E6100000F1F0F48FCF7E52C08E3F013813614440	New York City	New York City	United States of America
70	Philly DoPH Office	0101000020E6100000F5C3F4FF6DCA52C057008BDCDFF94340	1101 Market St	Philadelphia	United States of America
71	Vermont State Office	0101000020E6100000CA27F5FF9C2352C09E664B7EC11E4640	Vermont	Vermont	United States of America
72	Department of Ceviche Office	0101000020E6100000FFFFFFFF7C4253C0C6A2C2A5802828C0	Lima	Lima	Peru
\.


--
-- TOC entry 4259 (class 0 OID 0)
-- Dependencies: 240
-- Name: projects_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: geodimagiadmin
--

SELECT pg_catalog.setval('public.projects_location_id_seq', 72, true);


--
-- TOC entry 4104 (class 2606 OID 43383)
-- Name: projects_location projects_location_pkey; Type: CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_location
    ADD CONSTRAINT projects_location_pkey PRIMARY KEY (id);


--
-- TOC entry 4102 (class 1259 OID 43402)
-- Name: projects_location_location_2dc68923_id; Type: INDEX; Schema: public; Owner: geodimagiadmin
--

CREATE INDEX projects_location_location_2dc68923_id ON public.projects_location USING gist (location);


-- Completed on 2023-02-17 17:38:25

--
-- PostgreSQL database dump complete
--

