--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-17 17:42:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 245 (class 1259 OID 43397)
-- Name: projects_project_location; Type: TABLE; Schema: public; Owner: geodimagiadmin
--

CREATE TABLE public.projects_project_location (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    location_id bigint NOT NULL
);


ALTER TABLE public.projects_project_location OWNER TO geodimagiadmin;

--
-- TOC entry 244 (class 1259 OID 43396)
-- Name: projects_project_location_id_seq; Type: SEQUENCE; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE public.projects_project_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4258 (class 0 OID 43397)
-- Dependencies: 245
-- Data for Name: projects_project_location; Type: TABLE DATA; Schema: public; Owner: geodimagiadmin
--

COPY public.projects_project_location (id, project_id, location_id) FROM stdin;
7	2	7
8	1	8
9	1	9
10	1	10
11	3	11
12	4	12
13	5	13
14	5	14
15	5	15
16	5	16
17	5	17
18	6	18
19	7	19
20	7	20
21	7	21
22	7	22
23	7	23
24	7	24
25	8	25
26	9	26
27	10	27
28	11	28
29	11	29
30	11	30
31	12	32
32	12	33
33	12	31
34	13	34
35	13	35
36	13	36
37	13	37
38	13	38
39	13	39
40	14	40
41	15	41
42	16	42
43	17	43
44	18	44
45	18	45
46	19	46
47	20	47
48	21	49
49	22	50
50	23	51
51	23	52
52	23	53
53	24	54
54	25	56
55	25	57
56	25	58
57	25	59
58	25	60
59	25	61
60	25	62
61	26	63
64	29	65
65	30	66
66	31	67
67	32	68
68	33	69
69	34	70
70	35	71
71	36	72
\.


--
-- TOC entry 4264 (class 0 OID 0)
-- Dependencies: 244
-- Name: projects_project_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: geodimagiadmin
--

SELECT pg_catalog.setval('public.projects_project_location_id_seq', 71, true);


--
-- TOC entry 4104 (class 2606 OID 43401)
-- Name: projects_project_location projects_project_location_pkey; Type: CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_project_location
    ADD CONSTRAINT projects_project_location_pkey PRIMARY KEY (id);


--
-- TOC entry 4107 (class 2606 OID 43418)
-- Name: projects_project_location projects_project_location_project_id_location_id_0156a917_uniq; Type: CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_project_location
    ADD CONSTRAINT projects_project_location_project_id_location_id_0156a917_uniq UNIQUE (project_id, location_id);


--
-- TOC entry 4102 (class 1259 OID 43430)
-- Name: projects_project_location_location_id_ee739657; Type: INDEX; Schema: public; Owner: geodimagiadmin
--

CREATE INDEX projects_project_location_location_id_ee739657 ON public.projects_project_location USING btree (location_id);


--
-- TOC entry 4105 (class 1259 OID 43429)
-- Name: projects_project_location_project_id_175e7668; Type: INDEX; Schema: public; Owner: geodimagiadmin
--

CREATE INDEX projects_project_location_project_id_175e7668 ON public.projects_project_location USING btree (project_id);


--
-- TOC entry 4108 (class 2606 OID 43424)
-- Name: projects_project_location projects_project_loc_location_id_ee739657_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_project_location
    ADD CONSTRAINT projects_project_loc_location_id_ee739657_fk_projects_ FOREIGN KEY (location_id) REFERENCES public.projects_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4109 (class 2606 OID 43419)
-- Name: projects_project_location projects_project_loc_project_id_175e7668_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: geodimagiadmin
--

ALTER TABLE ONLY public.projects_project_location
    ADD CONSTRAINT projects_project_loc_project_id_175e7668_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2023-02-17 17:42:53

--
-- PostgreSQL database dump complete
--

